import type { Metadata } from "next";
import { Ubuntu, Inter, Poppins } from "next/font/google";


const rubik = Ubuntu({
    style: "normal",
    weight: ["400", "500", "700"],
    display: "swap",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SocialMood App",
    description: "Generated by create next app",
};

export default function BackofficeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="bg-white h-screen w-full antialiased min-h-screen flex items-center justify-center">
            {children}
        </main>

    );
}
