import type { Metadata } from "next";
import { Ubuntu, Inter, Poppins } from "next/font/google";
import "./globals.css";

const rubik = Ubuntu({
  style: "normal",
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SocialMood App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
